### ISSUE TITLE
[Sugestion] Tip Add chat with range

### ISSUE THREAD

**Issue by SrBedrock** [yusshu/CherryChat#1]
On servers with many players, the use of global chat becomes confusing when chatting with nearby players.
Adding chat where messages are visible only by close players helps a lot in organizing the chat.
Would it be possible to add a local chat with the distance for viewing the message configurable?

**Comment by yusshu** [comment]
It's ok!
Perfect
Soon in 0.2.0

**Comment by yusshu** [comment]
Success!!
https://www.spigotmc.org/resources/cherrychat-even-better-chat.65626/update?update=321607
